export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const CALCULATE_SUB_TOTAL = 'CALCULATE_SUB_TOTAL';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';